### ISSUE TITLE
Jekyll 4.0 support ?

### ISSUE THREAD

**Issue by nativerez** [brockfanning/jekyll-get-json#1]
Including this gem in my Gemfile forces the Jekyll dependency to use the older v3.8.6. Any chance it can be updated to work with Jekyll 4? Thanks

**Comment by SUPERCILEX** [comment]
@brockfanning Can we get a release since support for this has been merged in?

**Comment by brockfanning** [comment]
@SUPERCILEX Just pushed up version 0.0.2. Thanks for everyone's patience and help!

**Comment by SUPERCILEX** [comment]
Woohoo, thanks!

**Comment by MCOfficer** [comment]
if i understand correctly, this should be closed.

**Comment by brockfanning** [comment]
Sounds good, closing now.
