### ISSUE TITLE
Requested json not saving to _data directory

### ISSUE THREAD

**Issue by UrologyUnbound** [brockfanning/jekyll-get-json#11]
I had a similar issue referenced at #10 but I solved it by using my production endpoint: https://cms.herokuapp.com/articles. So maybe the local endpoint was my issue.

However, my data is not dumping into my specified config data file called articles. So, my json prints on my webpage but it doesn't create a file in my _data directory. Is this expected? Any suggestions on how I can create a file with the retrieved json? I tried setting target = Json.dump(source) but I am not experienced with ruby and it didn't work.

**Comment by brockfanning** [comment]
If I understand right, yes that is expected. This plugin does not download files, it only reads them into `site.data` where they can be used in Jekyll layouts and includes.

If you need to duplicate the json file itself (like if you want users to be able to download the json file) then you might want to link to the remote endpoint that you're already using. If you need it to be on your same website, then you could recreate it (I think) with a Jekyll file that uses "jsonify" on the data. Something like this (untested though):

```
---
permalink: myfile.json
---
{{ site.data.mydata | jsonify }}
```

**Comment by UrologyUnbound** [comment]
Thank you for putting me on the right track! I figured it out. I added to the converter.rb:
```
File.open(location, 'w') do |file|
    file.write(JSON.pretty_generate(source))
```
I hardcoded the location as `_data/articles.json` but I'll clean it up now that it's working. Maybe I can submit a pull request after I get it working nicely? Or fork it? I've never done either before, lol. Anyways, many thanks!
