### ISSUE TITLE
Change open() function to URI.open method

### ISSUE THREAD

**Issue by leics** [brockfanning/jekyll-get-json#4]
During builds Ruby fires warnings about deprecation of `open()` function demanding use of [URI.open](https://ruby-doc.org/stdlib-2.7.1/libdoc/open-uri/rdoc/OpenURI.html) instead of simple open() function, which now just returns empty strings.

**Comment by brockfanning** [comment]
This sounds like a simple change - PRs are welcome!

**Comment by dentarg** [comment]
@brockfanning I opened https://github.com/brockfanning/jekyll-get-json/pull/8
